name = "SequentExamples"
uuid = "ad14a6a2-213e-4da2-a0e0-035df608f96d"
authors = ["thautwarm <twshere@outlook.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
